### ISSUE TITLE
create a .toGanja operation for each of the types in Face.hs

### ISSUE THREAD

**Issue by julialongtin** [Haskell-Things/hslice#24]
https://enkimute.github.io/ganja.js/examples/coffeeshop.html#pga2d_points_and_lines

we need a function for each of the types, so that we can display them using the above.

**Comment by fisx** [comment]
Seems like you beat me to this one?  f3d64bbb

Is there anything still missing here, or can it be closed?

**Comment by julialongtin** [comment]
I suppose i did cover this. needed it for debugging. :)
