### ISSUE TITLE
Is this really a fork in the github sense?

### ISSUE THREAD

**Issue by fisx** [Haskell-Things/hslice#29]
I was wondering briefly which of this repo and https://github.com/nhalford/slicer I should aim my PR against, but I think it's this one, right?  Is there an easy way to detach the two repos and give credits in the readme instead?  Would be less confusing.

**Comment by julialongtin** [comment]
it's this one. i'll look into breaking the 'history', because this is confusing for me too.

**Comment by julialongtin** [comment]
fixed.
