### ISSUE TITLE
Graphics/Implicit/Definitions.hs:75:1: warning: [-Wtabs] dispite ls

### ISSUE THREAD

**Issue by wanfuse123** [Haskell-Things/HSlice#79]
abal v2-build --enable-profiling hslice
Resolving dependencies...
Build profile: -w ghc-8.8.4 -O1
In order, the following will be built (use -v for more details):
 - implicit-0.0.2 (lib:implicit) (requires build)
 - hslice-0.0.1 (lib) --enable-profiling (first run)
Starting     implicit-0.0.2 (all, legacy fallback)
Building     implicit-0.0.2 (all, legacy fallback)

Failed to build implicit-0.0.2.
Build log (
/home/stevena/.cabal/logs/ghc-8.8.4/implicit-0.0.2-e35f7e6da3394135e21007169e1eed025d46528aac0e1b06a1dae3be7dae022a.log
):
Configuring implicit-0.0.2...
Warning: 'ghc-options: -threaded' has no effect for libraries. It should only
be used for executables.
Warning: 'ghc-options: -rtsopts' has no effect for libraries. It should only
be used for executables.
Preprocessing executable 'extopenscad' for implicit-0.0.2..
Building executable 'extopenscad' for implicit-0.0.2..

<no location info>: warning: [-Wmissing-home-modules]
    These modules are needed for compilation but not listed in your .cabal file's other-modules: 
        Graphics.Implicit
        Graphics.Implicit.Definitions
        Graphics.Implicit.Export
        Graphics.Implicit.Export.Definitions
        Graphics.Implicit.Export.MarchingSquares
        Graphics.Implicit.Export.MarchingSquaresFill
        Graphics.Implicit.Export.NormedTriangleMeshFormats
        Graphics.Implicit.Export.PolylineFormats
        Graphics.Implicit.Export.Render
        Graphics.Implicit.Export.Render.Definitions
        Graphics.Implicit.Export.Render.GetLoops
        Graphics.Implicit.Export.Render.GetSegs
        Graphics.Implicit.Export.Render.HandleSquares
        Graphics.Implicit.Export.Render.Interpolate
        Graphics.Implicit.Export.Render.RefineSegs
        Graphics.Implicit.Export.Render.TesselateLoops
        Graphics.Implicit.Export.Symbolic.Rebound2
        Graphics.Implicit.Export.Symbolic.Rebound3
        Graphics.Implicit.Export.SymbolicFormats
        Graphics.Implicit.Export.SymbolicObj2
        Graphics.Implicit.Export.SymbolicObj3
        Graphics.Implicit.Export.TriangleMeshFormats
        Graphics.Implicit.Export.Util
        Graphics.Implicit.ExtOpenScad
        Graphics.Implicit.ExtOpenScad.Default
        Graphics.Implicit.ExtOpenScad.Definitions
        Graphics.Implicit.ExtOpenScad.Expressions
        Graphics.Implicit.ExtOpenScad.Primitives
        Graphics.Implicit.ExtOpenScad.Statements
        Graphics.Implicit.ExtOpenScad.Util
        Graphics.Implicit.ExtOpenScad.Util.ArgParser
        Graphics.Implicit.ExtOpenScad.Util.Computation
        Graphics.Implicit.MathUtil
        Graphics.Implicit.ObjectUtil
        Graphics.Implicit.ObjectUtil.GetBox2
        Graphics.Implicit.ObjectUtil.GetBox3
        Graphics.Implicit.ObjectUtil.GetImplicit2
        Graphics.Implicit.ObjectUtil.GetImplicit3
        Graphics.Implicit.Primitives
        Graphics.Implicit.SaneOperators
[ 1 of 41] Compiling Graphics.Implicit.Definitions ( Graphics/Implicit/Definitions.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Definitions.o )

Graphics/Implicit/Definitions.hs:75:1: warning: [-Wtabs]
    Tab character found here, and in 96 further locations.
    Please use spaces instead.
   |
75 |         -- Primitives
   | ^^^^^^^^
[ 2 of 41] Compiling Graphics.Implicit.Export.Definitions ( Graphics/Implicit/Export/Definitions.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/Definitions.o )

Graphics/Implicit/Export/Definitions.hs:12:1: warning: [-Wtabs]
    Tab character found here.
    Please use spaces instead.
   |
12 |         discreteAprox :: ℝ -> obj -> aprox
   | ^^^^^^^^
[ 3 of 41] Compiling Graphics.Implicit.Export.MarchingSquares ( Graphics/Implicit/Export/MarchingSquares.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/MarchingSquares.o )

Graphics/Implicit/Export/MarchingSquares.hs:16:1: warning: [-Wtabs]
    Tab character found here, and in 256 further locations.
    Please use spaces instead.
   |
16 |         let
   | ^^^^^^^^
[ 4 of 41] Compiling Graphics.Implicit.Export.MarchingSquaresFill ( Graphics/Implicit/Export/MarchingSquaresFill.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/MarchingSquaresFill.o )

Graphics/Implicit/Export/MarchingSquaresFill.hs:15:1: warning: [-Wtabs]
    Tab character found here, and in 174 further locations.
    Please use spaces instead.
   |
15 |         let
   | ^^^^^^^^
[ 5 of 41] Compiling Graphics.Implicit.Export.NormedTriangleMeshFormats ( Graphics/Implicit/Export/NormedTriangleMeshFormats.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/NormedTriangleMeshFormats.o )

Graphics/Implicit/Export/NormedTriangleMeshFormats.hs:9:1: warning: [-Wtabs]
    Tab character found here, and in 72 further locations.
    Please use spaces instead.
  |
9 |         where
  | ^^^^^^^^
[ 6 of 41] Compiling Graphics.Implicit.Export.PolylineFormats ( Graphics/Implicit/Export/PolylineFormats.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/PolylineFormats.o )

Graphics/Implicit/Export/PolylineFormats.hs:13:1: warning: [-Wtabs]
    Tab character found here, and in 102 further locations.
    Please use spaces instead.
   |
13 |         where
   | ^^^^^^^^
[ 7 of 41] Compiling Graphics.Implicit.Export.Render.Definitions ( Graphics/Implicit/Export/Render/Definitions.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/Render/Definitions.o )

Graphics/Implicit/Export/Render/Definitions.hs:12:1: warning: [-Wtabs]
    Tab character found here, and in one further location.
    Please use spaces instead.
   |
12 |         rnf (Sq b z xS yS) = rnf (b,z,xS,yS)
   | ^^^^^^^^
[ 8 of 41] Compiling Graphics.Implicit.Export.Render.GetLoops ( Graphics/Implicit/Export/Render/GetLoops.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/Render/GetLoops.o )

Graphics/Implicit/Export/Render/GetLoops.hs:16:1: warning: [-Wtabs]
    Tab character found here, and in 24 further locations.
    Please use spaces instead.
   |
16 |         workingLoop : getLoops' segs []
   | ^^^^^^^^
[ 9 of 41] Compiling Graphics.Implicit.Export.Render.Interpolate ( Graphics/Implicit/Export/Render/Interpolate.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/Render/Interpolate.o )

Graphics/Implicit/Export/Render/Interpolate.hs:8:1: warning: [-Wtabs]
    Tab character found here, and in 50 further locations.
    Please use spaces instead.
  |
8 |         let
  | ^^^^^^^^
[10 of 41] Compiling Graphics.Implicit.Export.SymbolicFormats ( Graphics/Implicit/Export/SymbolicFormats.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/SymbolicFormats.o )

Graphics/Implicit/Export/SymbolicFormats.hs:12:1: warning: [-Wtabs]
    Tab character found here, and in 52 further locations.
    Please use spaces instead.
   |
12 |         "union() {\n"
   | ^^^^^^^^
[11 of 41] Compiling Graphics.Implicit.Export.TriangleMeshFormats ( Graphics/Implicit/Export/TriangleMeshFormats.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/Export/TriangleMeshFormats.o )

Graphics/Implicit/Export/TriangleMeshFormats.hs:9:1: warning: [-Wtabs]
    Tab character found here, and in 132 further locations.
    Please use spaces instead.
  |
9 |         where
  | ^^^^^^^^
[12 of 41] Compiling Graphics.Implicit.ExtOpenScad.Definitions ( Graphics/Implicit/ExtOpenScad/Definitions.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/ExtOpenScad/Definitions.o )

Graphics/Implicit/ExtOpenScad/Definitions.hs:28:1: warning: [-Wtabs]
    Tab character found here, and in 96 further locations.
    Please use spaces instead.
   |
28 |                  | OBool Bool 
   | ^^^^^^^^
[13 of 41] Compiling Graphics.Implicit.ExtOpenScad.Expressions ( Graphics/Implicit/ExtOpenScad/Expressions.hs, dist/build/extopenscad/extopenscad-tmp/Graphics/Implicit/ExtOpenScad/Expressions.o )

Graphics/Implicit/ExtOpenScad/Expressions.hs:21:1: error:
    • Non type-variable argument
        in the constraint: Text.Parsec.Prim.Stream s m Char
      (Use FlexibleContexts to permit this)
    • When checking the inferred type
        pad :: forall s (m :: * -> *) u b.
               Text.Parsec.Prim.Stream s m Char =>
               Text.Parsec.Prim.ParsecT s u m b
               -> Text.Parsec.Prim.ParsecT s u m b
   |
21 | pad parser = do
   | ^^^^^^^^^^^^^^^...
cabal: Failed to build implicit-0.0.2 (which is required by hslice-0.0.1). See
the build log above for details.

make: *** [Makefile:121: dist-newstyle/build/x86_64-linux/ghc-8.8.4/hslice-0.0.1/build/Graphics/Hslice.o] Error 1

**Comment by sorki** [comment]
For some reason your build is picking up some very old version of `implicit`. Running `cabal v2-update` might fix it.

**Comment by julialongtin** [comment]
yep. this is my fault.

open hslice.cabal, and replace the "-any" of the line with 'implicit' on it to '<0.4.0.0 && > 0.2.0.0'

**Comment by wanfuse123** [comment]
thanks a lot! much appreciated!

**Comment by julialongtin** [comment]
merged fix to master. closing.
